apiVersion: v1
kind: ConfigMap
metadata:
  name: boundary-config
  labels:
    {{- include "boundary-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  creationTimestamp: null
data:
{{ (.Files.Glob "boundary-config.hcl").AsConfig | indent 4 }}
