{{- $fullName := include "boundary-chart.fullname" . }}
{{- $labels := include "boundary-chart.labels" . }}
{{- $selectorLabels := include "boundary-chart.selectorLabels" . }}
{{- range $index, $service := .Values.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-{{ $index }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  type: {{ $service.type }}
  {{- $type := $service.type }}
  ports:
    {{- range $service.ports }}
    - port: {{ .number }}
      targetPort: {{ .name }}
      {{- if eq $type "NodePort" }}
      nodePort: 30202
      {{- end }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    {{- $selectorLabels | nindent 4 }}
{{- end }}
