apiVersion: v1
kind: ConfigMap
metadata:
  name: boundary-config
  labels:
    {{- include "boundary-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  boundary-config-admin.hcl: |
    disable_mlock = true
    log_format    = "standard"
    controller {
      name        = "kubernetes-controller"
      description = "Boundary controller"
      database {
      url = "postgresql://{{.Values.database.username}}@{{ .Values.database.url }}:{{ .Values.database.port}}/{{.Values.database.dbName}}{{- if ne .Values.database.ssl true }}?sslmode=disable{{- end }}"
      }
      public_cluster_addr = "localhost"
    }
    worker {
      name        = "kubernetes-worker"
      description = "Boundary worker"
      address     = "localhost"
      controllers = ["localhost"]
      public_addr = "{{ .Values.publicAddress }}:{{ .Values.publicPort }}"
    }
    listener "tcp" {
      address     = "0.0.0.0"
      purpose     = "api"
      tls_disable = true
    }
    listener "tcp" {
      address     = "0.0.0.0"
      purpose     = "cluster"
      tls_disable = true
    }
    listener "tcp" {
      address     = "0.0.0.0"
      purpose     = "proxy"
      tls_disable = true
    }
    kms "awskms" {
      purpose    = "root"
      kms_key_id = "77a1d61f-3507-4314-bb7f-a84b82722fc3"
    }
    kms "awskms" {
      purpose    = "recovery"
      kms_key_id = "77a1d61f-3507-4314-bb7f-a84b82722fc3"
    }
    kms "awskms" {
      purpose    = "worker-auth"
      kms_key_id = "77a1d61f-3507-4314-bb7f-a84b82722fc3"
    }
    kms "awskms" {
      purpose    = "config"
      kms_key_id = "77a1d61f-3507-4314-bb7f-a84b82722fc3"
    }
  boundary-config.hcl: |
    disable_mlock = true
    log_format    = "standard"
    controller {
      name        = "kubernetes-controller"
      description = "Boundary controller"
      database {
      url = "postgresql://{{.Values.database.username}}:{{.Values.database.password}}@{{ .Values.database.url }}:{{ .Values.database.port}}/{{.Values.database.dbName}}{{- if ne .Values.database.ssl true }}?sslmode=disable{{- end }}"
      }
      public_cluster_addr = "localhost"
    }
    worker {
      name        = "kubernetes-worker"
      description = "Boundary worker"
      address     = "localhost"
      controllers = ["localhost"]
      public_addr = "{{ .Values.publicAddress }}:{{ .Values.publicPort }}"
    }
    listener "tcp" {
      address     = "0.0.0.0"
      purpose     = "api"
      tls_disable = true
    }
    listener "tcp" {
      address     = "0.0.0.0"
      purpose     = "cluster"
      tls_disable = true
    }
    listener "tcp" {
      address     = "0.0.0.0"
      purpose     = "proxy"
      tls_disable = true
    }
    kms "awskms" {
      purpose    = "root"
      kms_key_id = "77a1d61f-3507-4314-bb7f-a84b82722fc3"
    }
    kms "awskms" {
      purpose    = "recovery"
      kms_key_id = "77a1d61f-3507-4314-bb7f-a84b82722fc3"
    }
    kms "awskms" {
      purpose    = "worker-auth"
      kms_key_id = "77a1d61f-3507-4314-bb7f-a84b82722fc3"
    }
    kms "awskms" {
      purpose    = "config"
      kms_key_id = "77a1d61f-3507-4314-bb7f-a84b82722fc3"
    }
